### ISSUE TITLE
RTCPeerConnectionWeb's connectionState is calculated based on iceConnectionState vs connectionState

### ISSUE THREAD

**Issue by cterefinko** [flutter-webrtc/dart-webrtc#10]
[RTCPeerConnectionWeb](https://github.com/flutter-webrtc/dart-webrtc/blob/main/lib/src/rtc_peerconnection_impl.dart)'s connectionState is updated by `onIceConnectionStateChange` and is calculated based on `iceConnectionState`. The more appropriate `onConnectionStateChange` and `connectionState` aren't exposed via dart2js ([issue](https://github.com/dart-lang/sdk/issues/48735)).

Filing this issue to tracking updating to use those once added.

The effect of using iceConnectionState is that since [RTCIceConnectionState](https://www.w3.org/TR/webrtc/#rtciceconnectionstate-enum) has an extra 'checking' state vs [RTCPeerConnectionState](https://www.w3.org/TR/webrtc/#rtcpeerconnectionstate-enum), [`peerConnectionStateForString`](https://github.com/flutter-webrtc/webrtc-interface/blob/main/lib/src/enums.dart) reports `RTCPeerConnectionStateClosed ` for the unknown checking state.

**Comment by amantoux** [comment]
https://github.com/dart-lang/sdk/issues/48735 is available with Flutter 3.3
