### ISSUE TITLE
The non-abstract class 'MediaDevicesWeb' is missing implementations for these members:

### ISSUE THREAD

**Issue by zeroDivider** [flutter-webrtc/dart-webrtc#13]
Hi, from this morning, my pipelines fail due to (at least _it seems_) error in your lib:
```
/root/.pub-cache/hosted/pub.dartlang.org/dart_webrtc-1.0.6/lib/src/mediadevices_impl.dart:8:7:
Error: The non-abstract class 'MediaDevicesWeb' is missing implementations for these members:
 - MediaDevices.selectAudioOutput
class MediaDevicesWeb extends MediaDevices {
         ^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dartlang.org/webrtc_interface-1.0.6/lib/src/mediadevices.dart:125:27:
Info: 'MediaDevices.selectAudioOutput' is defined here.
  Future<MediaDeviceInfo> selectAudioOutput([AudioOutputOptions? options]);
                                              ^^^^^^^^^^^^^^^
Error: Compilation failed.
```
I guess it is due to new changes from [webrtc-interface](https://github.com/flutter-webrtc/webrtc-interface) from 4 hours ago.

Currently, my local env is working because of outdated cache, but cannot merge anything, we are blocked :(

**Comment by cloudwebrtc** [comment]
As a temporary workaround, you can modify `pubspec.lock` to fix `webrtc_interface` and `dart_webrtc `to the previous version.

**Comment by zeroDivider** [comment]
I use `webrtc_interface` transitively from yours lib. Also, we cannot revert since we have a lot of code and it may not be working as expected. Besides, we had similar problems lately with webrtc libs since you always use latest dependencies versions in your libs and downgrading has no effect.

**Comment by cloudwebrtc** [comment]
okay, I'll release a temporary fix version,

**Comment by cloudwebrtc** [comment]
@zeroDivider can you check again? I have released a new version
https://pub.dev/packages/webrtc_interface/versions/1.0.7

**Comment by zeroDivider** [comment]
https://github.com/flutter-webrtc/dart-webrtc/blob/main/pubspec.yaml
you are not using it here?

**Comment by cloudwebrtc** [comment]
dart_webrtc depends on webrtc_interface: ^1.0.6, which means that when webrtc_interface has a higher version, dart_webrtc will choose the highest version, so you only need to delete pubspec.lock and re `dart pub get` to depend on the latest webrtc_interface.
